# Generated by Django 4.1.7 on 2023-03-25 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of rating change'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Rating creation date'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'user')},
        ),
    ]
