# Generated by Django 4.1.7 on 2023-03-25 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_rating', '0002_alter_movie_options_rating_updated_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='updated_date',
        ),
    ]
